id: ADA6483DC
title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
type: translation
pechas:
- I7A09554C
- I7934000D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:52:15.100822
  last_modified_at: 2023-01-04 12:52:15.100849
  collections:
  - Khenpo Chimé Rigdzin Series
  - Works of Tibetan Masters
alignment_to_base:
  I7A09554C/032B: D72A
  I7934000D/888C: D72A
